version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - "npm install -g yarn"
      - "npm install -g typescript"
      - "touch .npmignore"
  pre_build:
    commands:
      - "yarn install --frozen-lockfile"
      - "yarn add tslib"
  build:
    commands:
      - "yarn build"
artifacts:
    type: zip
    files:
        - package.json
        - yarn.lock
        - 'dist/**/*'
        - node_modules/**/*
        - .ebextensions/**/*
        - .platform/**/*