/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILazlosRendering,
  ILazlosRenderingInterface,
} from "../../../../contracts/Types/Types.sol/ILazlosRendering";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "ingredientTokenMetadata",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "pizzaTokenMetadata",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ILazlosRendering__factory {
  static readonly abi = _abi;
  static createInterface(): ILazlosRenderingInterface {
    return new utils.Interface(_abi) as ILazlosRenderingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILazlosRendering {
    return new Contract(address, _abi, signerOrProvider) as ILazlosRendering;
  }
}
