/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILazlosPizzas,
  ILazlosPizzasInterface,
} from "../../../../contracts/Types/Types.sol/ILazlosPizzas";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "baker",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint16",
            name: "base",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "sauce",
            type: "uint16",
          },
          {
            internalType: "uint16[3]",
            name: "cheeses",
            type: "uint16[3]",
          },
          {
            internalType: "uint16[4]",
            name: "meats",
            type: "uint16[4]",
          },
          {
            internalType: "uint16[4]",
            name: "toppings",
            type: "uint16[4]",
          },
        ],
        internalType: "struct Pizza",
        name: "pizza",
        type: "tuple",
      },
    ],
    name: "bake",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "pizza",
    outputs: [
      {
        components: [
          {
            internalType: "uint16",
            name: "base",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "sauce",
            type: "uint16",
          },
          {
            internalType: "uint16[3]",
            name: "cheeses",
            type: "uint16[3]",
          },
          {
            internalType: "uint16[4]",
            name: "meats",
            type: "uint16[4]",
          },
          {
            internalType: "uint16[4]",
            name: "toppings",
            type: "uint16[4]",
          },
        ],
        internalType: "struct Pizza",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "baker",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "pizzaTokenId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint16",
            name: "base",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "sauce",
            type: "uint16",
          },
          {
            internalType: "uint16[3]",
            name: "cheeses",
            type: "uint16[3]",
          },
          {
            internalType: "uint16[4]",
            name: "meats",
            type: "uint16[4]",
          },
          {
            internalType: "uint16[4]",
            name: "toppings",
            type: "uint16[4]",
          },
        ],
        internalType: "struct Pizza",
        name: "pizza",
        type: "tuple",
      },
    ],
    name: "rebake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILazlosPizzas__factory {
  static readonly abi = _abi;
  static createInterface(): ILazlosPizzasInterface {
    return new utils.Interface(_abi) as ILazlosPizzasInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILazlosPizzas {
    return new Contract(address, _abi, signerOrProvider) as ILazlosPizzas;
  }
}
