/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ILazlosIngredients__factory } from "./ILazlosIngredients__factory";
export { ILazlosPizzas__factory } from "./ILazlosPizzas__factory";
export { ILazlosRendering__factory } from "./ILazlosRendering__factory";
