/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface ILazlosRenderingInterface extends utils.Interface {
  functions: {
    "ingredientTokenMetadata(uint256)": FunctionFragment;
    "pizzaTokenMetadata(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "ingredientTokenMetadata" | "pizzaTokenMetadata"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ingredientTokenMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pizzaTokenMetadata",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ingredientTokenMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pizzaTokenMetadata",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ILazlosRendering extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ILazlosRenderingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ingredientTokenMetadata(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    pizzaTokenMetadata(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  ingredientTokenMetadata(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  pizzaTokenMetadata(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    ingredientTokenMetadata(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    pizzaTokenMetadata(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ingredientTokenMetadata(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pizzaTokenMetadata(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ingredientTokenMetadata(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pizzaTokenMetadata(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
