/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILazlosIngredients } from "./ILazlosIngredients";
export type { ILazlosPizzas } from "./ILazlosPizzas";
export type { ILazlosRendering } from "./ILazlosRendering";
