/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155TokenReceiver } from "./ERC1155TokenReceiver";
export type { ERC1155U } from "./ERC1155U";
