/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC1155TokenReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155TokenReceiver__factory>;
    getContractFactory(
      name: "ERC1155U",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155U__factory>;
    getContractFactory(
      name: "ERC721TokenReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721TokenReceiver__factory>;
    getContractFactory(
      name: "ERC721U",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721U__factory>;
    getContractFactory(
      name: "LazlosIngredients",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LazlosIngredients__factory>;
    getContractFactory(
      name: "LazlosPizzas",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LazlosPizzas__factory>;
    getContractFactory(
      name: "LazlosPizzaShop",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LazlosPizzaShop__factory>;
    getContractFactory(
      name: "LazlosRendering",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LazlosRendering__factory>;
    getContractFactory(
      name: "ILazlosIngredients",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILazlosIngredients__factory>;
    getContractFactory(
      name: "ILazlosPizzas",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILazlosPizzas__factory>;
    getContractFactory(
      name: "ILazlosRendering",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILazlosRendering__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC1155TokenReceiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155TokenReceiver>;
    getContractAt(
      name: "ERC1155U",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155U>;
    getContractAt(
      name: "ERC721TokenReceiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721TokenReceiver>;
    getContractAt(
      name: "ERC721U",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721U>;
    getContractAt(
      name: "LazlosIngredients",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LazlosIngredients>;
    getContractAt(
      name: "LazlosPizzas",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LazlosPizzas>;
    getContractAt(
      name: "LazlosPizzaShop",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LazlosPizzaShop>;
    getContractAt(
      name: "LazlosRendering",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LazlosRendering>;
    getContractAt(
      name: "ILazlosIngredients",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILazlosIngredients>;
    getContractAt(
      name: "ILazlosPizzas",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILazlosPizzas>;
    getContractAt(
      name: "ILazlosRendering",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILazlosRendering>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
