/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155 from "./ERC1155";
export type { erc1155 };
import type * as erc721 from "./ERC721";
export type { erc721 };
import type * as types from "./Types";
export type { types };
export type { LazlosIngredients } from "./LazlosIngredients";
export type { LazlosPizzaShop } from "./LazlosPizzaShop";
export type { LazlosPizzas } from "./LazlosPizzas";
export type { LazlosRendering } from "./LazlosRendering";
